### ISSUE TITLE
Update for 1.0

### ISSUE THREAD

**Issue by jjspace** [Shoko84/BeatSaberDrinkWater#11]
Any chance we could get an update for 1.0+? It's such a simple mod but I really appreciated it to help prevent me getting too tired after playing for a while. Thanks!

**Comment by Shoko84** [comment]
Hi sorry for the late message :x 
I currently have little free time but I'll try to do it asap 👍

**Comment by Shoko84** [comment]
@jjspace It should be available on the BeatMods launcher or from the latest release on that GitHub
